module.exports = {
  searchButton: "#quick-search-expand",
  searchField: "#nav-quick-search",
  Product: "//a[contains(text(),'product')]",
  addCartButton: "#form-action-addToCart",
  checkoutButton: '[href="/checkout"]',
  emailField: "#email",
  checkButton: ".form-body > .form-field > .form-label",
  guestButton: '[data-test="customer-continue-as-guest-button"]',
  firstName: '[data-test="firstNameInput-text"]',
  lastName: '[data-test="lastNameInput-text"]',
  adress: '[data-test="addressLine1Input-text"]',
  city: '[data-test="cityInput-text"]',
  postalCode: '[data-test="postCodeInput-text"]',
  phoneNumber: '[data-test="phoneInput-text"]',
  continueButton: "//button[contains(text(),'Continue')]",
  cardNumber: "#ccNumber",
  ccvNumber: "#ccCvv",
  expiryDate: "#ccExpiry",
  nameCard: "#ccName",
  placeorderButton: "//button[contains(text(),'Place Order')]",
  ConfirmationTitle: "//h1[@class='optimizedCheckout-headingPrimary']",
  ConfirmationMessage: '[data-test="order-confirmation-order-status-text"]',
  productName: '[data-test="cart-item-product-title"]',
  firstnametext: ".staticConsignment > .vcard > .fn > .first-name",
  lastnametext: ".staticConsignment > .vcard > .fn > .family-name",
  emailtext: '[data-test="customer-info"]',
  phonetext: ".staticConsignment > .vcard > :nth-child(2) > .tel",
  addresstext: ".staticConsignment > .vcard > .adr > .street-address",
};
